drugs = [
    "Etizolam",
    "Troparil HBr",
    "3-MMC (Canada Only)",
    "Phenylpiracetam",
    "Allylescaline",
    "Escaline - 500mg",
    "Escaline - 1g",
    "Escaline - 3g",
    "Escaline - 5g",
    "N-(4-bromophenyl)adamantan-2-amine | Bromantane - 10g",
    "N-(4-bromophenyl)adamantan-2-amine | Bromantane - 1g",
    "N-(4-bromophenyl)adamantan-2-amine | Bromantane - 3g",
    "N-(4-bromophenyl)adamantan-2-amine | Bromantane - 500mg",
    "N-(4-bromophenyl)adamantan-2-amine | Bromantane - 5g",
    "Homomazindol - 50mg",
    "Homomazindol - 100mg",
    "Homomazindol - 250mg",
    "Homomazindol - 500mg",
    "Homomazindol - 1g",
    "Homomazindol - 3g",
    "Armodafinil - 1g",
    "Armodafinil - 3g",
    "Armodafinil - 5g",
    "Armodafinil - 10g",
    "Armodafinil - 20g",
    "Modafinil - 1g",
    "Modafinil - 3g",
    "Modafinil - 5g",
    "Modafinil - 10g",
    "Modafinil - 15g",
    "Modafinil - 20g",
    "Modafinil - 50g",
    "CRL-40,941 - 1G",
    "CRL-40,941 - 2G",
    "CRL-40,941 - 3G",
    "CRL-40,941 - 5G",
    "CRL-40,941 - 10G",
    "URB597 - 500mg",
    "URB597 - 1g",
    "URB597 - 3g",
    "URB597 - 5g",
    "3-(2-bromophenyl)-2-methylquinazolin-4(3H)-one | Mebroqualone - 500mg",
    "3-(2-bromophenyl)-2-methylquinazolin-4(3H)-one | Mebroqualone - 1g",
    "3-(2-bromophenyl)-2-methylquinazolin-4(3H)-one | Mebroqualone - 3g",
    "3-(2-bromophenyl)-2-methylquinazolin-4(3H)-one | Mebroqualone - 5g",
    "3-(2-bromophenyl)-2-methylquinazolin-4(3H)-one | Mebroqualone - 10g",
    "3-(2,4-dimethylphenyl)-2-methylquinazolin-4(3H)-one | Methylmethaqualone - 500mg",
    "3-(2,4-dimethylphenyl)-2-methylquinazolin-4(3H)-one | Methylmethaqualone - 1g",
    "3-(2,4-dimethylphenyl)-2-methylquinazolin-4(3H)-one | Methylmethaqualone - 3g",
    "3-(2,4-dimethylphenyl)-2-methylquinazolin-4(3H)-one | Methylmethaqualone - 5g",
    "3-(2,4-dimethylphenyl)-2-methylquinazolin-4(3H)-one | Methylmethaqualone - 10g",
    "Acetildenafil - 1g",
    "Acetildenafil - 500mg",
    "Acetildenafil - 3g",
    "Acetildenafil - 5g",
    "Acetildenafil - 10g",
    "Acetildenafil - 18g",
    "DMXB-A - 250mg",
    "GTS-21 | DMXB-A - 500mg",
    "GTS-21 | DMXB-A - 1g",
    "GTS-21 | DMXB-A - 3g",
    "GTS-21 | DMXB-A - 5g",
    "Baclofen - 250mg",
    "Baclofen - 500mg",
    "Baclofen - 1g",
    "Baclofen - 3g",
    "Baclofen - 5g",
    "Baclofen - 25g",
    "Phenylpiracetam - 3G",
    "Phenylpiracetam - 5G",
    "Phenylpiracetam - 10G",
    "Phenylpiracetam - 20G",
    "Phenylpiracetam - 250G",
    "Phenylpiracetam - 30G",
    "RRS-PDM-35",
    "3F-Phenmetrazine",
    "2-PHENYL-3,6-DIMETHYLMORPHOLINE | 3,6-DMPM - 500MG",
    "2-PHENYL-3,6-DIMETHYLMORPHOLINE | 3,6-DMPM - 1G",
    "2-PHENYL-3,6-DIMETHYLMORPHOLINE | 3,6-DMPM - 3G",
    "2-PHENYL-3,6-DIMETHYLMORPHOLINE | 3,6-DMPM - 5G",
    "2-PHENYL-3,6-DIMETHYLMORPHOLINE | 3,6-DMPM - 10G",
    "3-methyl-2-(3-methylphenyl)morpholine | 3-MePhenmetrazine - 500mg",
    "3-methyl-2-(3-methylphenyl)morpholine | 3-MePhenmetrazine - 1g",
    "3-methyl-2-(3-methylphenyl)morpholine | 3-MePhenmetrazine - 3g",
    "3-methyl-2-(3-methylphenyl)morpholine | 3-MePhenmetrazine - 5g",
    "2-phenyl-5,5-dimethylmorpholine | G-130 - 1g",
    "2-phenyl-5,5-dimethylmorpholine | G-130 - 3g",
    "2-phenyl-5,5-dimethylmorpholine | G-130 - 500mg",
    "2-phenyl-5,5-dimethylmorpholine | G-130 - 5g",
    "Isophenmetrazine - 250mg",
    "Isophenmetrazine - 500mg",
    "Isophenmetrazine - 1g",
    "Isophenmetrazine - 3g",
    "Isophenmetrazine - 5g",
    "Isophenmetrazine - 10g",
    "Mephenmetrazine - 250mg",
    "Mephenmetrazine - 500mg",
    "Mephenmetrazine - 1g",
    "Mephenmetrazine - 3g",
    "4-ethyl-2-hydroxy-3-methyl-2-phenylmorpholine | N-Ethylphenmetrazol - 500mg",
    "4-ethyl-2-hydroxy-3-methyl-2-phenylmorpholine | N-Ethylphenmetrazol - 1g",
    "4-ethyl-2-hydroxy-3-methyl-2-phenylmorpholine | N-Ethylphenmetrazol - 3g",
    "2-phenyl-3,5-dimethylmorpholine | PDM-35 - 1g",
    "2-phenyl-3,5-dimethylmorpholine | PDM-35 - 250mg",
    "2-phenyl-3,5-dimethylmorpholine | PDM-35 - 3g",
    "2-phenyl-3,5-dimethylmorpholine | PDM-35 - 500mg",
    "2-phenyl-3,5-dimethylmorpholine | PDM-35 - 5g",
    "4-ethyl-3-methyl-2-phenylmorpholine | Phenmetetrazine - 1g",
    "4-ethyl-3-methyl-2-phenylmorpholine | Phenmetetrazine - 3g",
    "4-ethyl-3-methyl-2-phenylmorpholine | Phenmetetrazine - 500mg",
    "(+)-isophenmetrazine - 50mg",
    "(+)-isophenmetrazine - 100mg",
    "(+)-isophenmetrazine - 250mg",
    "Phenetrazine - 500mg",
    "Phenetrazine - 1g",
    "Phenetrazine - 3g",
    "Phenetrazine - 5g",
    "3-fluorophenetrazine | 3F-Phenetrazine - 500mg",
    "3-fluorophenetrazine | 3F-Phenetrazine - 1g",
    "3-fluorophenetrazine | 3F-Phenetrazine - 3g",
    "Viloxazine - 1g",
    "Viloxazine - 3g",
    "Viloxazine - 500mg",
    "Viloxazine - 5g",
    "4-AcO-DMT | O-Acetylpsilocin",
    "DiPT - N,N-Diisopropyltryptamine",
    "DPT - N,N-Dipropyltryptamine",
    "4-AcO-DET - 500mg",
    "4-AcO-DET - 1g",
    "4-AcO-DET - 3g",
    "4-AcO-DET - 250mg",
    "4-AcO-MET - 125mg",
    "4-AcO-MET - 250mg",
    "4-AcO-MET - 500mg",
    "4-AcO-MET - 1g",
    "4-AcO-MET - 3g",
    "5-MeO-MiPT - 3g",
    "5-MeO-MiPT - 500mg",
    "5-MeO-MiPT - 1g",
    "5-MeO-MiPT - 5g",
    "5-MeO-MiPT - 250MG",
    "5-MeO-DMT - 125mg",
    "5-MeO-DMT - 250mg",
    "5-MeO-DMT - 500mg",
    "5-MeO-DMT - 1g",
    "5-MeO-DMT - 3g",
    "5-MeO-DMT - 5g",
    "5-MeO-DiPT - 1G",
    "5-MeO-DiPT - 500MG",
    "5-MeO-DiPT - 3G",
    "5-MeO-DiPT - 250MG",
    "5-MeO-DiPT - 5G",
    "4-HO-MET - 250mg",
    "4-HO-MET - 500mg",
    "4-HO-MET - 1g",
    "4-HO-MET - 3g",
    "Aniracetam",
    "Piracetam - 100g",
    "Piracetam - 250g",
    "Piracetam - 500g",
    "Oxiracetam - 10g",
    "Oxiracetam - 50g",
    "Oxiracetam - 100g",
    "Oxiracetam - 200g",
    "Ondansetron - 250mg",
    "Ondansetron - 500mg",
    "Ondansetron - 1g",
    "Ondansetron - 3g",
    "Tolazoline - 1g",
    "Tolazoline - 3g",
    "Tolazoline - 5g",
    "Tolazoline - 10g",
    "Tolazoline - 20g",
    "Loperamide",
    "Propylphenidate",
    "Bupivacaine - 5g",
    "Bupivacaine - 10g",
    "Bupivacaine - 25g",
    "Bupivacaine - 50g",
    "Bupivacaine - 100g",
    "Sildenafil Citrate",
    "Sildenafil Citrate - 250mg (Sample Size)",
    "Sunifiram - 1g",
    "Sunifiram - 3g",
    "Sunifiram - 5g",
    "Sunifiram - 10g",
    "Sunifiram - 15g",
    "Sunifiram - 20g",
    "GTS-21 | DMXB-A - 250mg",
    "HDMP-28 - 1g",
    "HDMP-28 - 3g",
    "HDMP-28 - 5g",
    "HDMP-28 - 10g",
    "1P-LSD (80mcg/ml Solution)",
    "Tadalafil",
    "Tianeptine sulfate",
    "L-THP",
    "Meldonium",
    "Memantine",
    "Pregnenolone",
    "THP",
    "alpha-GPC - 10g",
    "alpha-GPC - 25g",
    "alpha-GPC - 50g",
    "Ethyl 4-aminobenzoate | Benzocaine - 5g",
    "Ethyl 4-aminobenzoate | Benzocaine - 20g",
    "Ethyl 4-aminobenzoate | Benzocaine - 50g",
    "Ethyl 4-aminobenzoate | Benzocaine - 100g",
    "Ethyl 4-aminobenzoate | Benzocaine - 500g",
    "(HCl) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 1g",
    "(HCl) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 3g",
    "(HCl) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 5g",
    "(HCl) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 10g",
    "(HCl) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 15g",
    "(Base) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 1g",
    "(Base) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 3g",
    "(Base) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 5g",
    "(Base) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 10g",
    "(Base) - 5-(2-Chloroethyl)-4-methyl-1,3-thiazole | Clomethiazole - 15g",
    "Ibogaine - 1g",
    "5-Methoxy-2-indanamine - 500mg",
    "5-Methoxy-2-indanamine - 1g",
    "5-Methoxy-2-indanamine - 3g",
    "5-Methoxy-2-indanamine - 5g",
    "Gabapentin - 3g",
    "Gabapentin - 5g",
    "Gabapentin - 10g",
    "Gabapentin - 20g",
    "Gabapentin - 30g",
    "Gabapentin - 50g",
    "Iboga Total Alkaloid Extract - 1g",
    "Iboga Total Alkaloid Extract - 3g",
    "Iboga Total Alkaloid Extract - 5g",
    "Citicoline - 10g",
    "Citicoline - 30g",
    "Citicoline - 50g",
    "Huperzine A - 100MG",
    "Huperzine A - 250MG",
    "Huperzine A - 500MG",
    "Huperzine A - 1G",
    "Dextromethorphan | DXM - 2g",
    "Dextromethorphan | DXM - 5g",
    "Dextromethorphan | DXM - 10g",
    "Pregnenolone - 5g",
    "Procaine - 10G",
    "Procaine - 20G",
    "Procaine - 50G",
    "Procaine - 100G",
    "Procaine - 300G",
    "Procaine - 500G",
    "Tetrahydropalmatine | THP - 3G",
    "Tetrahydropalmatine | THP - 10G",
    "Tetrahydropalmatine | THP - 5G",
    "Sodium Valproate - 1g",
    "Sodium Valproate - 3g",
    "Sodium Valproate - 5g",
    "Sodium Valproate - 10g",
    "Sodium Valproate - 20g",
    "Sodium Valproate - 30g",
    "Sodium Valproate - 40g",
    "Sodium Valproate - 50g",
    "VINPOCETINE - 1G",
    "VINPOCETINE - 3G",
    "VINPOCETINE - 5G",
    "VINPOCETINE - 10G",
    "VINPOCETINE - 20G",
    "Mitragynine - 250mg",
    "Mitragynine - 500mg",
    "Mitragynine - 1g",
    "Mitragynine - 3gm",
    "Mitragynine - 5g",
    "Galantamine - 100mg",
    "Galantamine - 250mg",
    "Galantamine - 500mg",
    "Galantamine - 3g",
    "Galantamine - 1g"
]

import re

new_list = []

regex = r"^(.+) - .+$"


for drug in drugs:
    drug_name = re.sub(regex, r"\1", drug)
    new_list.append(drug_name)
    
unique_list = list(set(new_list))

# split names in format "name | synonym"
regex = r"(.+) [|] (.+)"
for drug in unique_list:
    matches = re.search(regex, drug)
    if matches is not None:
        unique_list.remove(drug)
        unique_list.append(matches.group(1))
        unique_list.append(matches.group(2))
        
with open("rechem_unique_drugs.txt", "w+") as f :
    for item in unique_list:
        f.write(item+"\n")